### ISSUE TITLE
Doc Mismatch for Admin address

### ISSUE THREAD

**Issue by benjaminbollen** [OpenST/organization-contracts#3]
*ST-06-002 Doc: Mismatch Between Comment and Code in Organization (Info)*

The docstring of the setAdmin function in the Organization contract does not match the actual implementation. As can be seen below, the function is described to be callable by the owner and admin, but only if the current admin calls the function, adminship shall be transferred immediately. However the code makes no such distinction. Further the description also indicates that it is discouraged to set the admin to the same address of the owner, but the contract makes no effort to prevent that.

Affected File:
/openst-contracts/contracts/organization/Organization.sol

Affected Code:
```
/**
 * @notice Sets the admin address. Can only be called by owner or current
 *         admin. If called by the current admin, adminship is transferred
 *         to the given address immediately.
 *         It is discouraged to set the admin address to be the same as the
 *         address of the owner. The point of the admin is to act on behalf
 *         of the organization without requiring the possibly very safely
 *         stored owner key(s).
 *         Admin can be set to `address(0)` if no admin is desired.
 *
 * @param _admin Admin address to be set.
 *
 * @return success_ True on successful execution.
 */
function setAdmin(
    address _admin
)
    external
    onlyOwnerOrAdmin
    returns (bool success_)
{
    /*
     * If the address does not change, the call is considered a success,
     * but we don't need to emit an event as it did not actually change.
     */
    if (admin != _admin) {
        emit AdminAddressChanged(_admin, admin);
        admin = _admin;
    }

    success_ = true;
}
```

**Comment by benjaminbollen** [comment]
action items:
1. `require(_admin != owner)`
2. update docs accordingly
3. remove `if` clause as premature optimization

**Comment by benjaminbollen** [comment]
So this is a breaking change; that s why it's in parking lot? @pgev

**Comment by pgev** [comment]
As per the ticket description, adding `require(owner != _admin)` will narrow down the requirements for the function, hence it would be a breaking change (semantic one). Moving to "Parking Lot" for now.

**Comment by benjaminbollen** [comment]
No interaction code that followed the doc would break, so I'm not considering this breaking code (semanticly).

**Comment by schemar** [comment]
```
 *         It is discouraged to set the admin address to be the same as the
 *         address of the owner. The point of the admin is to act on behalf
 *         of the organization without requiring the possibly very safely
 *         stored owner key(s).
```
Does not forbid to do that in my opinion. JLP definitely did that if I recall correctly. Maybe also mosaic.js?

**Comment by schemar** [comment]
It was reasoned back then to not forbid it. I don't recall the reasoning, though.

**Comment by pgev** [comment]
@benjaminbollen as it was not strongly stated (it requires, asserts, etc), but only encourages, I've agreed with @schemar that it's a breaking change. However, maybe that's me reading it like that, and if you think that it actually strong statement and documents function's contract, then we could proceed. Thx.
