### ISSUE TITLE
Publish NPM package

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/organization-contracts#8]
- Include ABI and BIN JSON files.
- Include autogenerated Contract interacts.
- Make sure that the publish command always generates the contract interacts for the latest contract.

Use package's `prepack`. Generally see the relevant developer guidelines section.

**Comment by schemar** [comment]
Do we need this *if* we decide to go with git-submodules for internal dependencies?

**Comment by benjaminbollen** [comment]
External users might want to use Organization or UtilityToken to build on it.  Organization for their own custom rules eg. or build different behaviour on UtilityToken, but they can start with gitsubmodule too.

For now let s not publish Organization and UtilityToken
